apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi
  name: multi
spec:
  containers:
    - name: multi1
      command:
        - /bin/sh
        - -c
        - echo hello;sleep 3600
      image: busybox
      resources: {}
    - name: multi2
      command:
        - /bin/sh
        - -c
        - echo hello;sleep 3600
      image: busybox
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
