apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx3
  name: nginx3
spec:
  initContainers:
  - image: busybox
    name: bbox
    command:
      - /bin/sh
      - -c
      - "wget -O /work-dir/index.html http://neverssl.com/online"
    volumeMounts:
      - name: vol
        mountPath: "/work-dir"
  containers:
  - image: nginx
    name: nginx3
    ports:
    - containerPort: 80
    resources: {}
    volumeMounts:
      - name: vol
        mountPath: "/usr/share/nginx/html"
  volumes:
    - name: vol
      emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
