apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: python-service
  name: python-service
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 5000
  selector:
    app: python-app
  type: LoadBalancer
status:
  loadBalancer: {}
