apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
    - args:
        - nginx
      image: nginx
      name: nginx
      resources: { }
      livenessProbe:
        periodSeconds: 5
        initialDelaySeconds: 5
        exec:
          command: [ "ls" ]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: { }
