apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mypod
  name: mypod
spec:
  containers:
    - name: c1
      command:
        - /bin/sh
        - -c
        - sleep 3600
      image: busybox
      resources: { }
      volumeMounts:
        - name: vol
          mountPath: /etc/foo
    - name: c2
      command:
        - /bin/sh
        - -c
        - sleep 3600
      image: busybox
      resources: { }
      volumeMounts:
        - name: vol
          mountPath: /etc/foo
  volumes:
    - name: vol
      emptyDir: { }
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: { }
