# pvc-definition.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  storageClassName: normal  # Optional
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi