apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: consumer
  name: consumer
  namespace: secret-ops
spec:
  containers:
  - image: nginx
    name: consumer
    resources: {}
    volumeMounts:
      - name: secvol
        mountPath: /var/app
        readOnly: true
  volumes:
    - name: secvol
      secret:
        secretName: my-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
