apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: null
  name: myrq
  namespace: one
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
status: {}
