apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secpod
  name: secpod
spec:
  containers:
  - image: nginx
    name: secpod
    resources: {}
    volumeMounts:
      - name: secvol
        mountPath: /etc/foo
  volumes:
    - name: secvol
      secret:
        secretName: mysecret2
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
