apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secpod
  name: secpod
spec:
  containers:
  - image: nginx
    name: secpod
    resources: {}
    env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret2
            key: username
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
