apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: userpod
  name: userpod
spec:
  serviceAccountName: myuser
  containers:
  - image: nginx
    name: userpod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
