apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxvol
  name: nginxvol
spec:
  containers:
  - image: nginx
    name: nginxvol
    resources: {}
    volumeMounts:
      - name: cmvol
        mountPath: /ect/lala
  volumes:
    - name: cmvol
      configMap:
        name: cmvolume
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
