apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mypod
  name: mypod
spec:
  nodeSelector:
    kubernetes.io/hostname: minikube
  tolerations:
    - key: "tier"
      operator: "Equal"
      value: "frontend"
      effect: "NoSchedule"
  containers:
    - image: nginx
      name: mypod
      resources: { }
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: { }
